#!/bin/sh
#
# Starts mender service.
#

start() {
	printf "Starting mender service: "
	umask 077

	start-stop-daemon -S -q -b -m -p /var/run/mender.pid \
		--exec /usr/bin/mender -- -log-file /var/log/mender -daemon
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping mender service: "
	start-stop-daemon -K -q -p /var/run/mender.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
